#version 430 core

#extension GL_ARB_compute_shader : enable
#extension GL_ARB_shader_storage_buffer_object : enable
//#extension GL_NV_gpu_shader5 : enable

layout(std430,binding = 0) buffer i{vec4 _input[];};
layout(std430,binding = 1) buffer o{vec4 _output[];};

uniform uint count;
layout( local_size_x = 128,  local_size_y = 1, local_size_z = 1) in;
void main () {
    uint gid = gl_GlobalInvocationID.x;
	if(gid < count){
        _output[gid] = _input[gid];
    }
}